export default {
  //头部状态
  headerState:0,
  address:'',
  //食品列表
  foodList:[],
  //商家信息
  shopList:[],
  //用户信息
  userInfo:{},
  goods:[],
  //购物车数组
  shopCar:[],
  carItemIndex:{},
  //是否显示Food组件
  isShowFood:false,
  //Food组件内容所需对象。
  foodObj:{foodIndex:'',goodIndex:'',foodName:''},
}
